name: CI/CD

on:
    push:
        branches: [master]

permissions:
    id-token: write # Required for OIDC
    contents: write # To push version bump commit

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '24'
                  registry-url: 'https://registry.npmjs.org'

            # Ensure npm 11.5.1 or later for trusted publishing
            - name: Update npm
              run: npm install -g npm@latest

            - name: Install dependencies
              run: npm i

            - name: Ensure clean working tree
              run: |
                  if [[ -n "$(git status --porcelain)" ]]; then
                      echo "Working tree is dirty before version bump. Resetting changes."
                      git status --short
                      git reset --hard
                      git clean -fd
                  fi

            - name: Set git user
              run: |
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"

            - name: Bump version
              run: npm version patch

            - name: Push version bump
              run: |
                  git push origin HEAD:master

            - name: Publish to npm
              run: npm publish --access public
